version: "3.2"

services:
  redis:
    image: "redis:alpine"
    command: redis-server
    # expose:
    #   - "6379"
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

volumes:
  redis-data:
  redis-conf:
